---
- hosts: all
  become: yes
  vars:
    myvar1: tree
    myvar2: git
    myvar3: apache2
  tasks:
      - name: i want to display variable value
        debug:
            msg: "{{myvar1}}"

      - name: i want to install git tree and apacge2
        apt:
           name: "{{item}}"
           state: present
        loop:
        - "{{myvar1}}"
        - "{{myvar2}}"
        - "{{myvar3}}"


            